### ISSUE TITLE
Rewrite it in rust

### ISSUE THREAD

**Issue by ghost** [LekKit/RVVM#65] opened 2022-12-04 16:09 UTC
This project need some enhancements. You know that.

**Comment by flrdv** [comment] 2022-12-04 16:09
agree

**Comment by LedinecMing** [comment] 2022-12-04 16:10
upvote

**Comment by epoll-reactor** [comment] 2022-12-04 16:42
```
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

; Function Attrs: noinline nounwind optnone sspstrong uwtable
define dso_local i32 @main() #0 {
  %0 = alloca [1 x [2 x [3 x [4 x [5 x [6 x i32]]]]]], align 4
  %1 = load [1 x [2 x [3 x [4 x [5 x [6 x i32]]]]]], [1 x [2 x [3 x [4 x [5 x [6 x i32]]]]]]* %0, align 4
  %2 = getelementptr inbounds [1 x [2 x [3 x [4 x [5 x [6 x i32]]]]]], [1 x [2 x [3 x [4 x [5 x [6 x i32]]]]]]* %0, i32 0, i32 0
  %3 = getelementptr inbounds [2 x [3 x [4 x [5 x [6 x i32]]]]], [2 x [3 x [4 x [5 x [6 x i32]]]]]* %2, i32 0, i32 0
  %4 = getelementptr inbounds [3 x [4 x [5 x [6 x i32]]]], [3 x [4 x [5 x [6 x i32]]]]* %3, i32 0, i32 0
  %5 = getelementptr inbounds [4 x [5 x [6 x i32]]], [4 x [5 x [6 x i32]]]* %4, i32 0, i32 0
  %6 = getelementptr inbounds [5 x [6 x i32]], [5 x [6 x i32]]* %5, i32 0, i32 0
  %7 = getelementptr inbounds [6 x i32], [6 x i32]* %6, i32 0, i32 0
  %8 = load i32, i32* %7, align 4
  store i32 2, i32* %7, align 4
  %9 = load [1 x [2 x [3 x [4 x [5 x [6 x i32]]]]]], [1 x [2 x [3 x [4 x [5 x [6 x i32]]]]]]* %0, align 4
  %10 = getelementptr inbounds [1 x [2 x [3 x [4 x [5 x [6 x i32]]]]]], [1 x [2 x [3 x [4 x [5 x [6 x i32]]]]]]* %0, i32 0, i32 0
  %11 = getelementptr inbounds [2 x [3 x [4 x [5 x [6 x i32]]]]], [2 x [3 x [4 x [5 x [6 x i32]]]]]* %10, i32 0, i32 0
  %12 = getelementptr inbounds [3 x [4 x [5 x [6 x i32]]]], [3 x [4 x [5 x [6 x i32]]]]* %11, i32 0, i32 0
  %13 = getelementptr inbounds [4 x [5 x [6 x i32]]], [4 x [5 x [6 x i32]]]* %12, i32 0, i32 0
  %14 = getelementptr inbounds [5 x [6 x i32]], [5 x [6 x i32]]* %13, i32 0, i32 0
  %15 = getelementptr inbounds [6 x i32], [6 x i32]* %14, i32 0, i32 0
  ret i32* %15
}

attributes #0 = { noinline nounwind optnone sspstrong uwtable "frame-pointer"="all" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }

!llvm.module.flags = !{!0, !1, !2, !3, !4}
!llvm.ident = !{!5}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 7, !"PIC Level", i32 2}
!2 = !{i32 7, !"PIE Level", i32 2}
!3 = !{i32 7, !"uwtable", i32 1}
!4 = !{i32 7, !"frame-pointer", i32 2}
!5 = !{!"clang version 14.0.6"}
```

**Comment by epoll-reactor** [comment] 2022-12-04 17:03
Possible duplicate of #35

**Comment by Mr0maks** [comment] 2022-12-04 19:32
![can-we-ban-this-guy](https://user-images.githubusercontent.com/24385314/205511504-ca0fb48f-a945-4aef-bd13-448503e8dd90.gif)

**Comment by adamierymenko** [comment] 2022-12-07 13:40
Not an objectively bad idea and not as hard as it sounds, but also probably not necessary. Safe languages are awesome and Rust is awesome but a JIT is inherently unsafe anyway, so any Rust port is going to be full of "unsafe" keywords.

Now if this were library-ified it could certainly be packaged as a Rust crate.

**Comment by adamierymenko** [comment] 2022-12-07 16:29
![rust](https://user-images.githubusercontent.com/591635/206235449-318b19ea-dd36-4a1d-aa14-4754477d4bc3.png)

**Comment by ghost** [comment] 2022-12-09 19:31
> Not an objectively bad idea and not as hard as it sounds, but also probably not necessary. Safe languages are awesome and Rust is awesome but a JIT is inherently unsafe anyway, so any Rust port is going to be full of "unsafe" keywords.
> 
> Now if this were library-ified it could certainly be packaged as a Rust crate.

This issue is not serious at all, but I had plans to write safe wrapper around RVVM's public API ([here](https://crates.io/crates/rvvm-sys) the raw ffi bindings), maybe we can return to this idea possibly later.

This issue is not closed only at my request, so treat it like local-meme.

**Closed as completed** 2023-01-29 22:47 UTC
